#!/bin/bash

set -e

../venv/bin/python add_device.py pyri_variable_storage variable_storage
../venv/bin/python add_device.py pyri_devices_states devices_states
../venv/bin/python add_device.py pyri_sandbox sandbox
../venv/bin/python add_device.py pyri_robotics_jog_service robotics_jog
../venv/bin/python add_device.py pyri_camera_viewer_service vision_camera_viewer
../venv/bin/python add_device.py pyri_camera_calibration_service vision_camera_calibration
../venv/bin/python add_device.py pyri_vision_robot_calibration_service vision_robot_calibration
../venv/bin/python add_device.py pyri_aruco_detection_service vision_aruco_detection
../venv/bin/python add_device.py pyri_template_matching_service vision_template_matching
../venv/bin/python add_device.py pyri_robotics_motion_service robotics_motion
