#!/bin/bash

set -e

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd $SCRIPTPATH/..

if [ -f venv/Scripts/python.exe ]; then
  echo Python virtual environment already created, exiting
    exit
fi

python3 -m venv venv
