#!/bin/bash

set -e

export ROBOTRACONTEUR_LOG_LEVEL=INFO
export ROBOTRACONTEUR_PYTHON_TRACEBACK_PRINT_EXC=1

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd $SCRIPTPATH/..

source ./venv/bin/activate

python -m pyri.robotics.robotics_jog_service
