#!/bin/bash

gnome-terminal \
  --tab --title="variable_storage" -e ./run_variable_storage \
  --tab --title="device_manager" -e ./run_device_manager \
  --tab --title="devices_states" -e ./run_devices_states \
  --tab --title="sandbox" -e ./run_sandbox \
  --tab --title="webui_server" -e ./run_webui_server \
  --tab --title="jog_joint" -e ./run_jog_joint \
  --tab --title="jog_cart" -e ./run_jog_cart
