#!/bin/bash

gnome-terminal \
  --tab --title="variable_storage" -e ./run_variable_storage \
  --tab --title="device_manager" -e ./run_device_manager \
  --tab --title="devices_states" -e ./run_devices_states \
  --tab --title="sandbox" -e ./run_sandbox \
  --tab --title="webui_server" -e ./run_webui_server \
  --tab --title="robotics_jog" -e ./run_robotics_jog \
  --tab --title="vision_camera_viewer" -e ./run_vision_camera_viewer \
  --tab --title="vision_camera_calibration" -e ./run_vision_calibration \
  --tab --title="vision_robot_calibration" -e ./run_vision_robot_calibration \
  --tab --title="vision_template_matching" -e ./run_vision_template_matching \
  --tab --title="vision_aruco_detection" -e ./run_vision_aruco_detection \
  --tab --title="robotics_motion" -e ./run_robotics_motion


