#!/bin/bash

set -e

export ROBOTRACONTEUR_LOG_LEVEL=INFO
export ROBOTRACONTEUR_PYTHON_TRACEBACK_PRINT_EXC=1

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd $SCRIPTPATH/..

source ./venv/bin/activate

python -m pyri.devices_states --device-info-file=pyri-devices-states/config/pyri_devices_states_default_info.yml --device-manager-url=rr+tcp://localhost:59902?service=device_manager --robotraconteur-tcp-ipv4-discovery=true
