#!/bin/bash

set -e

export ROBOTRACONTEUR_LOG_LEVEL=INFO
export ROBOTRACONTEUR_PYTHON_TRACEBACK_PRINT_EXC=1

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")

cd $SCRIPTPATH/..

source ./venv/bin/activate

python -m pyri.device_manager --device-info-file=pyri-device-manager/config/pyri_device_manager_default_info.yml --variable-storage-url=rr+tcp://localhost:59901?service=variable_storage --robotraconteur-tcp-ipv4-discovery=true
